using System.Collections.Generic;
using System.IO;
using System.Linq;
using DJTechRuntime.PCG;
using UnityEditor;
using UnityEngine;

namespace DJTechEditor.PCG.Graph
{
    /// <summary>
    /// Loads the builtin subgraph library index (BuiltinLibrary/library-index.json)
    /// so the search window can offer packaged .pcgsubgraph assets alongside
    /// manifest node types. Index and assets are generated by
    /// scripts/build_library_index.py from the repo-level library/ directory.
    /// </summary>
    [InitializeOnLoad]
    public static class PcgBuiltinLibrary
    {
        public sealed class LibraryPin
        {
            public string id = "";
            public string name = "";
            public string pinType = "Any";
        }

        public sealed class LibraryItem
        {
            public string id = "";
            public string displayName = "";
            public string category = "";
            public string file = "";
            public string assetVersion = "";
            public string contentHash = "";
            public string description = "";
            public List<string> keywords = new();
            public List<LibraryPin> inputs = new();
            public List<LibraryPin> outputs = new();
        }

        private const string RootFolder = "Assets/PcgPlugin/Editor/BuiltinLibrary";
        private const string IndexPath = RootFolder + "/library-index.json";
        private const string EntryPrefix = "library:";

        private static List<LibraryItem> _items = new();
        private static bool _loaded;

        static PcgBuiltinLibrary()
        {
            EditorApplication.delayCall += () => EnsureLoaded();
        }

        public static IReadOnlyList<LibraryItem> All
        {
            get { EnsureLoaded(); return _items; }
        }

        public static void Reload() => _loaded = false;

        public static bool TryFind(string id, out LibraryItem item)
        {
            EnsureLoaded();
            item = _items.FirstOrDefault(candidate => candidate.id == id);
            return item != null;
        }

        public static IEnumerable<IGrouping<string, LibraryItem>> ByCategory() =>
            All.GroupBy(item => string.IsNullOrEmpty(item.category) ? "Other" : item.category)
               .OrderBy(group => group.Key);

        public static string MakeSearchUserData(LibraryItem item) => EntryPrefix + item.id;

        public static bool TryParseSearchUserData(object userData, out LibraryItem item)
        {
            item = null;
            if (userData is not string text || !text.StartsWith(EntryPrefix, System.StringComparison.Ordinal))
                return false;
            return TryFind(text.Substring(EntryPrefix.Length), out item);
        }

        public static string AssetPathFor(LibraryItem item) =>
            item == null ? null : $"{RootFolder}/{item.file}";

        public static bool TryLoadAsset(LibraryItem item, out string guid, out PcgSubgraphAsset asset)
        {
            guid = null;
            asset = null;
            var path = AssetPathFor(item);
            if (string.IsNullOrEmpty(path))
                return false;
            guid = AssetDatabase.AssetPathToGUID(path);
            if (string.IsNullOrEmpty(guid))
                return false;
            asset = AssetDatabase.LoadAssetAtPath<PcgSubgraphAsset>(path);
            return asset != null;
        }

        public static bool HasCompatibleInput(LibraryItem item, string pinType)
        {
            if (item == null || string.IsNullOrEmpty(pinType))
                return false;
            return item.inputs.Any(pin =>
                pin.pinType == "Any" || PcgNodeManifest.PinTypesCompatible(pinType, pin.pinType));
        }

        public static bool HasCompatibleOutput(LibraryItem item, string pinType)
        {
            if (item == null || string.IsNullOrEmpty(pinType))
                return false;
            return item.outputs.Any(pin =>
                pin.pinType == "Any" || PcgNodeManifest.PinTypesCompatible(pinType, pin.pinType));
        }

        private static void EnsureLoaded()
        {
            if (_loaded)
                return;
            _loaded = true;
            _items = new List<LibraryItem>();

            if (!File.Exists(IndexPath))
                return;

            try
            {
                var root = PcgMiniJson.Deserialize(File.ReadAllText(IndexPath)) as Dictionary<string, object>;
                if (root == null ||
                    !root.TryGetValue("items", out var itemsObj) ||
                    itemsObj is not List<object> items)
                    return;

                foreach (var itemObj in items)
                {
                    if (itemObj is not Dictionary<string, object> json)
                        continue;
                    _items.Add(new LibraryItem
                    {
                        id = GetString(json, "id"),
                        displayName = GetString(json, "displayName"),
                        category = GetString(json, "category"),
                        file = GetString(json, "file"),
                        assetVersion = GetString(json, "assetVersion"),
                        contentHash = GetString(json, "contentHash"),
                        description = GetString(json, "description"),
                        keywords = GetStringList(json, "keywords"),
                        inputs = GetPins(json, "inputs"),
                        outputs = GetPins(json, "outputs"),
                    });
                }
            }
            catch (System.Exception ex)
            {
                Debug.LogWarning($"[PCG] Failed to load builtin library index: {ex.Message}");
            }
        }

        private static string GetString(Dictionary<string, object> json, string key) =>
            json.TryGetValue(key, out var value) ? value?.ToString() ?? "" : "";

        private static List<string> GetStringList(Dictionary<string, object> json, string key)
        {
            var list = new List<string>();
            if (json.TryGetValue(key, out var value) && value is List<object> entries)
                list.AddRange(entries.Select(entry => entry?.ToString() ?? "").Where(text => text.Length > 0));
            return list;
        }

        private static List<LibraryPin> GetPins(Dictionary<string, object> json, string key)
        {
            var pins = new List<LibraryPin>();
            if (!json.TryGetValue(key, out var value) || value is not List<object> entries)
                return pins;
            foreach (var entry in entries)
            {
                if (entry is not Dictionary<string, object> pinJson)
                    continue;
                pins.Add(new LibraryPin
                {
                    id = GetString(pinJson, "id"),
                    name = GetString(pinJson, "name"),
                    pinType = string.IsNullOrEmpty(GetString(pinJson, "pinType")) ? "Any" : GetString(pinJson, "pinType"),
                });
            }
            return pins;
        }
    }
}
