# CMake generated Testfile for 
# Source directory: /Users/djhuang/PCG-AI/pcg-core
# Build directory: /Users/djhuang/PCG-AI/pcg-core/build-debug
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_executor]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_executor")
set_tests_properties([=[test_executor]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;124;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_data]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_data")
set_tests_properties([=[test_data]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;125;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_phase41]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_phase41")
set_tests_properties([=[test_phase41]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;126;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_phase42]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_phase42")
set_tests_properties([=[test_phase42]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;127;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_phase43]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_phase43")
set_tests_properties([=[test_phase43]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;128;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_phase44]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_phase44")
set_tests_properties([=[test_phase44]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;134;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_cook_cache]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_cook_cache")
set_tests_properties([=[test_cook_cache]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;140;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_spawn_mesh_binary]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_spawn_mesh_binary")
set_tests_properties([=[test_spawn_mesh_binary]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;146;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_phase45_spline]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_phase45_spline")
set_tests_properties([=[test_phase45_spline]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;152;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_phase46]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_phase46")
set_tests_properties([=[test_phase46]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;158;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_bridge_bevel]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_bridge_bevel")
set_tests_properties([=[test_bridge_bevel]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;164;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_stone_arch_bridge]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_stone_arch_bridge")
set_tests_properties([=[test_stone_arch_bridge]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;170;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_robust_predicates]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_robust_predicates")
set_tests_properties([=[test_robust_predicates]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;178;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_tri_intersect]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_tri_intersect")
set_tests_properties([=[test_tri_intersect]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;184;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_bvh]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_bvh")
set_tests_properties([=[test_bvh]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;190;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_imesh]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_imesh")
set_tests_properties([=[test_imesh]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;196;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_arrangement]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_arrangement")
set_tests_properties([=[test_arrangement]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;202;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_boolean_output]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_boolean_output")
set_tests_properties([=[test_boolean_output]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;208;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_boolean_binary]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_boolean_binary")
set_tests_properties([=[test_boolean_binary]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;214;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_boolean]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_boolean")
set_tests_properties([=[test_boolean]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;222;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_boolean_graph]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_boolean_graph")
set_tests_properties([=[test_boolean_graph]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;228;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
add_test([=[test_boolean_bevel_chain]=] "/Users/djhuang/PCG-AI/pcg-core/build-debug/test_boolean_bevel_chain")
set_tests_properties([=[test_boolean_bevel_chain]=] PROPERTIES  WORKING_DIRECTORY "/Users/djhuang/PCG-AI/pcg-core/tests" _BACKTRACE_TRIPLES "/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;234;add_test;/Users/djhuang/PCG-AI/pcg-core/CMakeLists.txt;0;")
subdirs("_deps/json-build")
