#!/usr/bin/env python3
"""Generate the public node reference from the canonical node manifest."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "schema" / "node-manifest.json"
OUTPUT_PATH = ROOT / "docs" / "node-reference.md"


def text(value: object) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, (dict, list)):
        return f"`{json.dumps(value, ensure_ascii=False, separators=(',', ':'))}`"
    value_text = str(value)
    return f"`{value_text}`" if value_text else "`\"\"`"


def pin_table(pins: list[dict[str, object]]) -> list[str]:
    if not pins:
        return ["None.", ""]
    lines = ["| ID | Label | Type |", "| --- | --- | --- |"]
    for pin in pins:
        lines.append(
            f"| `{pin.get('id', '')}` | {pin.get('label', '')} | `{pin.get('pinType', '')}` |"
        )
    lines.append("")
    return lines


def property_table(properties: dict[str, dict[str, object]]) -> list[str]:
    if not properties:
        return ["None.", ""]
    lines = [
        "| Property | Type | Default | Range or options |",
        "| --- | --- | --- | --- |",
    ]
    for name, definition in properties.items():
        constraints: list[str] = []
        if "minimum" in definition:
            constraints.append(f"min {definition['minimum']}")
        if "maximum" in definition:
            constraints.append(f"max {definition['maximum']}")
        if "enum" in definition:
            constraints.append(
                ", ".join(f"`{item}`" for item in definition.get("enum", []))
            )
        lines.append(
            f"| `{name}` | `{definition.get('type', '')}` | {text(definition.get('default'))} | "
            f"{'<br>'.join(constraints) or '—'} |"
        )
    lines.append("")
    return lines


def main() -> None:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    nodes = manifest.get("nodes", [])
    categories: dict[str, list[dict[str, object]]] = {}
    for node in nodes:
        categories.setdefault(str(node.get("category", "Other")), []).append(node)

    lines = [
        "# Node Reference",
        "",
        f"This file is generated from `schema/node-manifest.json` version `{manifest.get('version', '')}`. "
        f"It documents {len(nodes)} manifest-backed node types. The manifest and native runtime remain the authoritative contracts.",
        "",
        "> Do not edit this file by hand. Run `python3 scripts/generate-node-reference.py` after changing the manifest.",
        "",
        "## Categories",
        "",
    ]

    for category in sorted(categories):
        anchor = category.lower().replace(" ", "-")
        lines.append(f"- [{category}](#{anchor}) ({len(categories[category])})")
    lines.append("")

    for category in sorted(categories):
        lines.extend([f"## {category}", ""])
        for node in sorted(categories[category], key=lambda item: str(item.get("type", ""))):
            node_type = str(node.get("type", ""))
            lines.extend(
                [
                    f"### {node_type}",
                    "",
                    f"**Display name:** {node.get('displayName', node_type)}",
                    f"**Category:** `{category}`",
                    "",
                ]
            )
            description = node.get("description")
            if description:
                lines.extend([str(description), ""])
            lines.extend(["#### Inputs", ""])
            lines.extend(pin_table(node.get("inputs", [])))
            lines.extend(["#### Outputs", ""])
            lines.extend(pin_table(node.get("outputs", [])))
            lines.extend(["#### Properties", ""])
            lines.extend(property_table(node.get("properties", {})))

    OUTPUT_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Generated {OUTPUT_PATH.relative_to(ROOT)} with {len(nodes)} nodes.")


if __name__ == "__main__":
    main()
